### ISSUE TITLE
Invalid auth token for Blynk console 2.0

### ISSUE THREAD

**Issue by bmustata** [blynkkk/lib-python#50]
Is blynk going to update this library with support for console 2.0?

https://github.com/blynkkk/blynk-library
https://github.com/vshymanskyy/blynk-library-python

I used the token from:
https://blynk.cloud/dashboard/...

```
import time
import logging
import BlynkLib

BLYNK_AUTH = 'auth code' #insert your Auth Token here

# initialize Blynk
blynk = BlynkLib.Blynk(BLYNK_AUTH)

# @blynk.on("connected")
# def connect_handler(ping):
#     print('Blynk connected')

# @blynk.on("disconnected")
# def disconnect_handler():
#     print('Blynk disconnected')

print('starting device...')

# main loop that starts program and handles registered events
try:
    while True:
        blynk.run()
except KeyboardInterrupt:
    blynk.disconnect()
    print("Blynk disconnected!")
```

Error message
```
    ___  __          __
   / _ )/ /_ _____  / /__
  / _  / / // / _ \/  '_/
 /____/_/\_, /_//_/_/\_\
        /___/ for Python v0.2.0 (Darwin)

starting device...
Invalid auth token
```

**Comment by Kmmel** [comment]
@bmustata saw the same issue with the lib from `https://github.com/vshymanskyy/blynk-library-python`. 
It seems like the examples in this repo `blynkkk/lib-python` have not been updated as you need to import `blynklib` and not `BlinkLib`, that means you also need to adjust 

```blynk = BlynkLib.Blynk(BLYNK_AUTH)``` 

to 

```blynk = blynklib.Blynk(BLYNK_AUTH)```.

After that I could at least see that it says `v0.2.6` instead of` v0.2.0` and the auth token error message is gone.

**Comment by bmustata** [comment]
Working nice with the [Blynk Server](https://github.com/blynkkk/blynk-server)

**Comment by bmustata** [comment]
Blynk Server was just removed from GitHub.
